spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: 'admin'
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'